apiVersion: 'kubevirt.io/v1'
kind: 'VirtualMachine'
metadata:
  name: 'win10-proper-swordfish'
  namespace: 'md-siemens-vms'
spec:
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        creationTimestamp: null
        name: 'win10-proper-swordfish'
      spec:
        sourceRef:
          kind: 'DataSource'
          name: 'win10'
          namespace: 'openshift-virtualization-os-images'
        storage:
          resources:
            requests:
              storage: '60Gi'
    - metadata:
        creationTimestamp: null
        name: 'win10-proper-swordfish-disk-similar-giraffe'
      spec:
        preallocation: false
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: '30Gi'
          storageClassName: 'ocs-storagecluster-ceph-rbd'
  running: false
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: 'medium'
        vm.kubevirt.io/os: 'windows10'
        vm.kubevirt.io/workload: 'desktop'
      creationTimestamp: null
      labels:
        kubevirt.io/domain: 'win10-proper-swordfish'
        kubevirt.io/size: 'medium'
    spec:
      architecture: 'amd64'
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: 'delay'
            rtc:
              tickPolicy: 'catchup'
          utc: {}
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: 'sata'
              name: 'rootdisk'
            - cdrom:
                bus: 'sata'
              name: 'windows-drivers-disk'
            - disk:
                bus: 'virtio'
              name: 'disk-similar-giraffe'
          inputs:
            - bus: 'usb'
              name: 'tablet'
              type: 'tablet'
          interfaces:
            - macAddress: '02:06:b6:00:00:14'
              masquerade: {}
              model: 'e1000e'
              name: 'default'
        features:
          acpi: {}
          apic: {}
          hyperv:
            frequencies: {}
            ipi: {}
            reenlightenment: {}
            relaxed: {}
            reset: {}
            runtime: {}
            spinlocks:
              spinlocks: 8191
            synic: {}
            synictimer:
              direct: {}
            tlbflush: {}
            vapic: {}
            vpindex: {}
        machine:
          type: 'pc-q35-rhel9.2.0'
        memory:
          guest: '8Gi'
        resources: {}
      networks:
        - name: 'default'
          pod: {}
      terminationGracePeriodSeconds: 3600
      volumes:
        - dataVolume:
            name: 'win10-proper-swordfish'
          name: 'rootdisk'
        - containerDisk:
            image: 'registry.redhat.io/container-native-virtualization/virtio-win-rhel9@sha256:aff867adb2b9f6a82b8a6047e415a961a90ca63a196c21d8446cd51aa3265aab'
          name: 'windows-drivers-disk'
        - dataVolume:
            name: 'win10-proper-swordfish-disk-similar-giraffe'
          name: 'disk-similar-giraffe'
