apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: max-debian-ievd
  namespace: md-siemens-vms
  finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
  labels:
    app: max-debian-ievd
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: max-debian-ievd
      spec:
        sourceRef:
          kind: DataSource
          name: siemens-ievd
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 25Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: max-debian-ievd
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - macAddress: '02:4c:25:00:00:04'
              masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: max-debian-ievd
          name: rootdisk

