apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: win10-max-gitops
    vm.kubevirt.io/template: windows10-desktop-medium
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.31.1
  name: win10-max-gitops
  namespace: md-vms-gitops
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        creationTimestamp: null
        name: win10-max-gitops
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 60Gi
    - metadata:
        creationTimestamp: null
        name: win10-max-gitops-installation-cdrom
      spec:
        source:
          pvc:
            name: win10-install-iso
            namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: '16106127360'
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: windows10
        vm.kubevirt.io/workload: desktop
      creationTimestamp: null
      labels:
        kubevirt.io/domain: win10-max-gitops
        kubevirt.io/size: medium
    spec:
      architecture: amd64
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
            - bootOrder: 2
              disk:
                bus: sata
              name: rootdisk
            - bootOrder: 3
              cdrom:
                bus: sata
              name: windows-drivers-disk
            - bootOrder: 1
              cdrom:
                bus: sata
              name: installation-cdrom
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - macAddress: '02:f5:ee:00:00:33'
              masquerade: {}
              model: e1000e
              name: default
        features:
          acpi: {}
          apic: {}
          hyperv:
            frequencies: {}
            ipi: {}
            reenlightenment: {}
            relaxed: {}
            reset: {}
            runtime: {}
            spinlocks:
              spinlocks: 8191
            synic: {}
            synictimer:
              direct: {}
            tlbflush: {}
            vapic: {}
            vpindex: {}
          smm: {}
        firmware:
          bootloader:
            efi:
              secureBoot: true
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 8Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 3600
      volumes:
        - dataVolume:
            name: win10-max-gitops
          name: rootdisk
        - containerDisk:
            image: 'registry.redhat.io/container-native-virtualization/virtio-win-rhel9@sha256:ad14f311b4a0f3e10c514f4242da39f9a14dc1ba8e99d5b996ea61d055538c39'
          name: windows-drivers-disk
        - dataVolume:
            name: win10-max-gitops-installation-cdrom
          name: installation-cdrom
